finetune:
  # run_id: '26v8lrkc'
  run_id: '1cm2z6yo'
  # run_id: '24uhbe8m'
  preset: 'none'
  dataset: 'rgz'
  n_classes: 2 
  iterations: 10
  n_layers: 10
  lr_decay: 0.75
  n_epochs: 100
  batch_size: 50
  test_frac: 0.3
  early_stopping: False

trainer:
  gpus: 1 # set to 1 to disable multi gpu training
  num_nodes: 1
  strategy: null # set to null to disable multi gpu training
  fast_dev_run: False # debugging mode
  precision: 32 # [16, 32, 'bf16'], often overriden
  deterministic: True
