type: 'mae'
project_name: 'debug-byol'
dataset: 'stl10' # ['imagenette', 'rgz', 'gzmnist', 'gz2', 'stl10', 'cifar10']
debug: True
seed: 0

dataloading:
  num_workers: 8  # often overriden
  prefetch_factor: 30
  persistent_workers: False  # torch default is False
  pin_memory: True
  val_batch_size: 500 # validation batch size

evaluation:
  knn_eval: False
  linear_eval: True
  ridge_eval: True
  n_eval_epochs: 1
  checkpoint_mode: 'last'
  early_stopping: False
  n_iterations: 1
  topk: 5
  check_val_every_n_epoch: 5

compute: 'slurm'
precision: 32 # [16, 32, 'bf16'], often overriden
profiler: 'none'
