preset: null
model:
    architecture: 'resnet18' 
    features: 100     # Number of encoded features (null just uses original resnet output)
    n_epochs: 200
    downscale: True

data:
    color_channels: 1
    classes: 2
    rotate: True
    conf_test: 0.5
    unc_test: 0
    val_size: 0.2
    val_batch_size: 500
    input_height: 128 

linear:
    n_epochs: 100
    opt: 'adam'
    lr: 0.2
    batch_size: 25
    momentum: 0.9
    weight_decay: 0
    scheduler: 'cosine'

knn:
  neighbors: 20
  temperature: 0.1
  leave_first_out: True

## DATA ## 
cut_threshold: 10

## AUGMENTATIONS ##
center_crop_size: 70
# blur_sig: !!python/tuple [0.1, 2.0]

## Optimiser ## 
# Base settings
lr: 0.0002
momentum: 0.9
weight_decay: 0.0005
batch_size: 50
opt: 'adam'
# Scheduler
scheduler: 'cosine' # ['none', 'cosine', 'warmupcosine']
warmup_epochs: 10  # Only used in linear warmup cosine annealing

# LARS
lars: False
trust_coef: 0.003
