preset: 'none'

model:
    n_epochs: 1000
    m: 0.996 # Controls EMA hyperparameter for BYOL momentum encoder
    m_decay: False

    architecture:
        preset: 'resnet34' # ['resnet18', 'resnet34', 'resnet50', 'none']
        features: 512     # Number of encoded features (null just uses original resnet output)
        downscale: True
        block_type: 'basic'
        layers: !!python/tuple [1, 2, 2, 1]

    projection_head:
        hidden: 512
        out: 256

    optimizer:
      type: 'sgd'
      lr: 0.2 # Note this will be scaled with batch_size so best to leave
      momentum: 0.9
      weight_decay: 0.0000015 # 0.0005
      beta_1: 0.9
      beta_2: 0.999
      lars: False
      trust_coef: 0.003

    scheduler:
      decay_type: 'warmupcosine' # ['none', 'cosine', 'warmupcosine']
      warmup_epochs: 10  # Only used in linear warmup cosine annealing, if scheduler type is 'warmupcosine'

data:
    color_channels: 1
    classes: 2
    rotate: True
    input_height: 128 # Keep this at 128 and adjust center_crop_size
    batch_size: 1024 
    val_batch_size: 500
    cut_threshold: 27
    test_frac: 0.3 

linear:
    n_epochs: 100
    opt: 'adam'
    lr: 0.0003
    batch_size: 300
    momentum: 0
    nesterov: False
    weight_decay: 0

## DATA ## 
augmentations:
  center_crop_size: 80
  random_crop_scale: !!python/tuple [0.8, 1]
  p_radio: 0.5
  p_blur: 0
  s: 0.5
  p_aug: 0.5
